# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(db_index=True, max_length=16, unique=True)),
                ('nickname', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=8)),
                ('birthday', models.DateField()),
                ('avatar', models.CharField(max_length=256)),
                ('location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('合肥', '合肥')], max_length=16)),
            ],
        ),
    ]
